### PR TITLE
removed mut attributes, fixed warnings while compiling

### PR DESCRIPTION
**Pull request by gianlucamazza**
Hello Peter,

I had two errors today trying to compile with rust 1.45.0-nightly, I fixed quickly hope is ok.

➜  proofmarshal git:(master) cargo build
   Compiling owned v0.1.0
   Compiling singlelife v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/singlelife)
   Compiling leint v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/leint)
   Compiling fake-simd v0.1.2
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> singlelife/src/lib.rs:1:1
  |
1 | #![feature(arbitrary_self_types)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling opaque-debug v0.2.3
   Compiling static_assertions v1.1.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
   Compiling sliceinit v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/sliceinit)
error: could not compile `singlelife`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

### CODE REVIEW

**Comment by gianlucamazza** [comment]
this is the original warning I had without cargo nightly version:

➜  proofmarshal git:(master) cargo build
   Compiling proc-macro2 v1.0.18
   Compiling unicode-xid v0.2.0
   Compiling typenum v1.12.0
   Compiling syn v1.0.30
   Compiling byteorder v1.3.4
   Compiling libc v0.2.71
   Compiling byte-tools v0.3.1
   Compiling bitflags v1.2.1
   Compiling proc-macro-hack v0.5.16
   Compiling leint v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/leint)
   Compiling fake-simd v0.1.2
   Compiling singlelife v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/singlelife)
   Compiling opaque-debug v0.2.3
   Compiling static_assertions v1.1.0
   Compiling sliceinit v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/sliceinit)
   Compiling owned v0.1.0
   Compiling anyref v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/anyref)
   Compiling owned v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/owned)
   Compiling block-padding v0.1.5
   Compiling quote v1.0.6
   Compiling hex-literal-impl v0.2.2
   Compiling memmap v0.7.0
   Compiling generic-array v0.12.3
   Compiling hex-literal v0.2.1
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling sha2 v0.8.2
   Compiling thiserror-impl v1.0.19
   Compiling thiserror v1.0.19
   Compiling hoard v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/hoard)
warning: variable does not need to be mutable
   --> hoard/src/journal/mod.rs:238:19
    |
238 |     fn alloc_blob(mut self, size: usize) -> Result<Self::WriteBlob, Self::Error> {
    |                   ----^^^^
    |                   |
    |                   help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

   Compiling proofmarshal-core v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/proofmarshal-core)
use std::cmp;
use std::convert::{TryFrom, TryInto};
use std::fs::{File, OpenOptions};
use std::io::{self, Write, Seek, SeekFrom};
use std::marker::PhantomData;
use std::mem::{self, MaybeUninit};
use std::path::Path;
use std::slice;
use std::sync::Arc;

use memmap::Mmap;

use crate::Le;
use crate::pointee::Pointee;
use crate::offset::{OffsetMut, Offset};
use crate::pile::TryPile;
use crate::save::{self, SavePtr, SaveBlob, Save, SavePoll};

mod wordoffset;
use self::wordoffset::{Word, WordOffset};

#[derive(Debug)]
pub struct Journal<'p, H = ()> {
    marker: PhantomData<fn(&'p ()) -> &'p H>,
    mapping: Arc<Mmap>,
}

impl<H> Clone for Journal<'_, H> {
    fn clone(&self) -> Self {
        Self {
            marker: PhantomData,
            mapping: self.mapping.clone(),
        }
    }
}

impl<'p, H> Journal<'p, H> {
    pub fn open(path: impl AsRef<Path>) -> io::Result<Self> {
        let fd = OpenOptions::new()
                             .read(true)
                             .open(path)?;
        Self::open_fd(&fd)
    }

    pub fn open_fd(fd: &File) -> io::Result<Self> {
        Ok(Self {
            marker: PhantomData,
            mapping: Self::make_mapping(fd)?,
        })
    }
:238
impl<'p, 'v, H> SavePtr for JournalWriter<'v, 'p, H> {
use std::cmp;
use std::convert::{TryFrom, TryInto};
use std::fs::{File, OpenOptions};
use std::io::{self, Write, Seek, SeekFrom};
use std::marker::PhantomData;
use std::mem::{self, MaybeUninit};
use std::path::Path;
use std::slice;
use std::sync::Arc;

use memmap::Mmap;

use crate::Le;
use crate::pointee::Pointee;
use crate::offset::{OffsetMut, Offset};
use crate::pile::TryPile;
use crate::save::{self, SavePtr, SaveBlob, Save, SavePoll};

mod wordoffset;
use self::wordoffset::{Word, WordOffset};

#[derive(Debug)]
pub struct Journal<'p, H = ()> {
    marker: PhantomData<fn(&'p ()) -> &'p H>,
    mapping: Arc<Mmap>,
}

impl<H> Clone for Journal<'_, H> {
    fn clone(&self) -> Self {
        Self {
            marker: PhantomData,
            mapping: self.mapping.clone(),
        }
    }
}

impl<'p, H> Journal<'p, H> {
    pub fn open(path: impl AsRef<Path>) -> io::Result<Self> {
        let fd = OpenOptions::new()
                             .read(true)
                             .open(path)?;
        Self::open_fd(&fd)
    }

    pub fn open_fd(fd: &File) -> io::Result<Self> {
        Ok(Self {
            marker: PhantomData,
            mapping: Self::make_mapping(fd)?,
        })
    }
:162
warning: 1 warning emitted
use super::*;

use std::error::Error;
use std::ops::Deref;
use thiserror::Error;

use hoard::blob::*;
use hoard::load::*;
use hoard::save::*;
use hoard::primitive::Primitive;
use hoard::ptr::{Ptr, AsPtr};

use super::flags::ValidateFlagsBlobError;

#[derive(Debug, Error)]
#[error("FIXME")]
pub enum ValidateSumTreeDataBlobError<SumError: Error, PtrError: Error> {
    Flags(<Flags as ValidateBlob>::Error),
    Sum(SumError),
    Ptr(PtrError),
}

impl<T, S, P> ValidateBlob for SumTreeData<T, S, P>
where S: ValidateBlob,
      P: ValidateBlob,
{
    const BLOB_LEN: usize = <u8 as ValidateBlob>::BLOB_LEN +
                            <Digest as ValidateBlob>::BLOB_LEN +
                            <S as ValidateBlob>::BLOB_LEN +
                            <P as ValidateBlob>::BLOB_LEN;

    type Error = ValidateSumTreeDataBlobError<<S as ValidateBlob>::Error, <P as ValidateBlob>::Error>;

    fn validate_blob<'a>(mut blob: BlobValidator<'a, Self>) -> Result<ValidBlob<'a, Self>, Self::Error> {
        blob.field::<Flags>().map_err(ValidateSumTreeDataBlobError::Flags)?;
        blob.field::<Digest>().into_ok();
        blob.field::<S>().map_err(ValidateSumTreeDataBlobError::Sum)?;
        blob.field::<P>().map_err(ValidateSumTreeDataBlobError::Ptr)?;
        unsafe { Ok(blob.finish()) }
    }
}

impl<Q: Ptr, T, S, P> Decode<Q> for SumTreeData<T, S, P>
where S: Decode<Q>,
      P: Decode<Q>,
{
    fn decode_blob(mut blob: BlobDecoder<Q, Self>) -> Self {
        unsafe {
            Self {
                marker: PhantomData,
:162
impl<Q: Ptr, T, S, P: Ptr> Decode<Q> for Inner<T, S, P>

   Compiling proofmarshal-collections v0.1.0 (/Users/gianluca/workspace/sparringparrots/proofmarshal/proofmarshal-collections)
warning: variable does not need to be mutable
   --> proofmarshal-collections/src/tree/marshal_impls.rs:162:26
    |
162 |     fn validate_blob<'a>(mut blob: BlobValidator<'a, Self>) -> Result<ValidBlob<'a, Self>, Self::Error> {
    |                          ----^^^^
    |                          |
    |                          help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 20.82s

**Comment by gianlucamazza** [comment]
this fix has not tested properly or discussed.
